server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.211.195:33060/stu_management_sys?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: zwl
    password: zzczwl1425
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #初始连接池大小
      min-idle: 5 #最小空闲连接数
      max-active: 20 #最大活动数
      max-wait: 60000 #获取连接的最大等待时间
      time-between-eviction-runs-millis: 600000  # 两次连接回收之间的时间间隔
      min-evictable-idle-time-millis: 600000  # 连接在池中最小生存的时间
      validation-query: SELECT 1  # 验证连接是否有效的 SQL 查询语句
      test-while-idle: true  # 空闲时是否检查连接的可用性
      test-on-borrow: false  # 获取连接时是否检查连接的可用性
      test-on-return: false  # 归还连接时是否检查连接的可用性
      pool-prepared-statements: true  # 是否缓存 PreparedStatement，默认为 true
      max-pool-prepared-statement-per-connection-size: 20  # 每个连接上的 PreparedStatement 缓存数量
      filters: stat,wall,log4j2  # 连接过滤器列表
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 连接附加属性
  redis:
    host: 101.37.211.195    #Redis 地址
    port: 33061             #Redis 端口
    password: zzczwl1425    #Redis 密码，如果没有留空
    database: 0             #使用的数据库
    timeout: 5000ms          #连接超时

  mail:
    host: smtp.163.com            #SMTP 服务器地址（按你实际邮箱配置）
    username: zwl1425@163.com     #发件邮箱
    password: CBTkVX4n4nhxYkiH    #SMTP 授权码，不是登录密码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.itzhangmanage.pojo
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
  #mybatis 分页插件
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql